[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make -f make_mac.mak'

# カラーテーマ
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# 下にあるバーを修飾
[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
# emmet
repo =  'mattn/emmet-vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# コメントON/OFFを手軽に実行
[[plugins]]
repo = 'tomtom/tcomment_vim'

# シンタックスチェック
[[plugins]]
repo =  'scrooloose/syntastic.git'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'derekwyatt/vim-scala'

