[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

# カラーテーマ
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# 下にあるバーを修飾
[[plugins]]
repo =  'itchyny/lightline.vim'

