[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
# rubyやc/c++やbashのタグを自動で閉じる
repo =  'tpope/vim-endwise'

[[plugins]]
# コードを自動で閉じてくれる
repo =  'Townk/vim-autoclose'

[[plugins]]
# c#の補完
repo = 'OrangeT/vim-csharp'

# vimのコピペがオートインデントされるのを修正
[[plugins]]
repo =  'ConradIrwin/vim-bracketed-paste'

# ファイラー
[[plugins]]
repo =  'Shougo/vimfiler'
depends = ['vimproc.vim']

# コメントON/OFFを手軽に実行
[[plugins]]
repo =  'tomtom/tcomment_vim'

# PHPをPCRで自動整形
[[plugins]]
repo =  'stephpy/vim-php-cs-fixer'

# ctagsのタグファイル生成をファイル保存時に自動実行できる
[[plugins]]
repo =  'soramugi/auto-ctags.vim'

# シンタックスチェック
[[plugins]]
repo =  'scrooloose/syntastic.git'

[[plugins]]
repo =  'jceb/vim-hier'

# 高速grep
[[plugins]]
repo =  'rking/ag.vim'

